enhancement: add creation time to the permission object
owncloud/libre-graph-api pull request #179
Opened 2024-04-24 14:21 UTC by fschade

the c-time is not part of the official ms spec, that means were extending the permission object with a creationDateTime object property.

not sure how we proceed with that (not part of the official spec), lets discuss it here!

Needed by: https://github.com/owncloud/ocis/issues/8749

2024-04-24 14:36 UTC, 2403905 submitted a review, later dismissed

2024-04-25 07:23 UTC, rhafer requested changes

2024-04-25 07:23 UTC, rhafer commented on api/openapi-spec/v1.0.yaml
> +          description: An optional creation date.
Actually I was referring to add the note the the description. Like we do e.g. here:
https://github.com/owncloud/libre-graph-api/blob/main/api/openapi-spec/v1.0.yaml#L4222

2024-04-25 08:56 UTC, rhafer approved these changes

2024-04-25 08:58 UTC, merged