Add user groups
owncloud/libre-graph-api pull request #18
Opened 2021-12-14 13:49 UTC by micbar

# Description

## Add User endpoints

`/users/{User-ID}`
`/users/`

## Add group schema

With a selected set of properties

## Add group endpoints

`/groups/`
`/groups/{Group-ID}`

2021-12-14 15:58 UTC, rhafer requested changes
I think we shouldn't be adding all of those attributes that we're likely to never support (but I guess I can live with that)

Please fix the `directorObject` description though.

2021-12-14 15:58 UTC, rhafer commented on api/openapi-spec/v0.0.yaml
> +          nullable: true
What's reason for adding all of these? I doubt we will need any of this anytime soon, if we ever need it.

As already mentioned elsewhere, I somehow think we should be the list of attributes small for now (if only to avoid confusion about what we actually support).

2021-12-14 15:58 UTC, rhafer commented on api/openapi-spec/v0.0.yaml
> +      nullable: true
The description of `directoryObject` seems wrong. (copy and paste error?)

2021-12-15 13:35 UTC, micbar commented on api/openapi-spec/v0.0.yaml
> +      nullable: true
yes. Corrected.

2021-12-15 14:07 UTC, rhafer approved these changes

2021-12-15 15:04 UTC, refs approved these changes

2021-12-15 15:05 UTC, merged