Switch back to upstream openapi-generator
owncloud/libre-graph-api pull request #33
Opened 2022-03-02 11:28 UTC by dschmidt

... and pin it to a fixed version.

2022-03-02 12:09 UTC, micbar commented on .drone.star
> +	'openapi-generator-image': 'openapitools/openapi-generator-cli:latest'
could you pin that to the current commID?

2022-03-02 12:09 UTC, micbar requested changes
Let us pin the version

2022-03-02 13:09 UTC, dschmidt commented on .drone.star
> +	'openapi-generator-image': 'openapitools/openapi-generator-cli:latest'
No. I don't think they publish docker images for every commit:

https://hub.docker.com/r/openapitools/openapi-generator-cli/tags

2022-03-02 13:54 UTC, micbar commented on .drone.star
> +	'openapi-generator-image': 'openapitools/openapi-generator-cli:latest'
ok then let us pin 5.4.0

2022-03-03 13:01 UTC, micbar approved these changes

2022-03-03 13:05 UTC, merged